# LAB | Feature Engineering

**Load the data**

In this challenge, we will be working with the same Spaceship Titanic data, like the previous Lab. The data can be found here:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/spaceship_titanic.csv

Metadata

https://github.com/data-bootcamp-v4/data/blob/main/spaceship_titanic.md

In [56]:
#Libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [57]:
spaceship = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/spaceship_titanic.csv")
spaceship.head()

PassengerId HomePlanet CryoSleep  Cabin  Destination   Age    VIP  \
0     0001_01     Europa     False  B/0/P  TRAPPIST-1e  39.0  False   
1     0002_01      Earth     False  F/0/S  TRAPPIST-1e  24.0  False   
2     0003_01     Europa     False  A/0/S  TRAPPIST-1e  58.0   True   
3     0003_02     Europa     False  A/0/S  TRAPPIST-1e  33.0  False   
4     0004_01      Earth     False  F/1/S  TRAPPIST-1e  16.0  False   

   RoomService  FoodCourt  ShoppingMall     Spa  VRDeck               Name  \
0          0.0        0.0           0.0     0.0     0.0    Maham Ofracculy   
1        109.0        9.0          25.0   549.0    44.0       Juanna Vines   
2         43.0     3576.0           0.0  6715.0    49.0      Altark Susent   
3          0.0     1283.0         371.0  3329.0   193.0       Solam Susent   
4        303.0       70.0         151.0   565.0     2.0  Willy Santantines   

   Transported  
0        False  
1         True  
2        False  
3        False  
4         True

**Check the shape of your data**

In [58]:
spaceship.shape

(8693, 14)

**Check for data types**

In [59]:
spaceship.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   PassengerId   8693 non-null   object 
 1   HomePlanet    8492 non-null   object 
 2   CryoSleep     8476 non-null   object 
 3   Cabin         8494 non-null   object 
 4   Destination   8511 non-null   object 
 5   Age           8514 non-null   float64
 6   VIP           8490 non-null   object 
 7   RoomService   8512 non-null   float64
 8   FoodCourt     8510 non-null   float64
 9   ShoppingMall  8485 non-null   float64
 10  Spa           8510 non-null   float64
 11  VRDeck        8505 non-null   float64
 12  Name          8493 non-null   object 
 13  Transported   8693 non-null   bool   
dtypes: bool(1), float64(6), object(7)
memory usage: 891.5+ KB


**Check for missing values**

In [60]:
spaceship.isna().sum()

PassengerId       0
HomePlanet      201
CryoSleep       217
Cabin           199
Destination     182
Age             179
VIP             203
RoomService     181
FoodCourt       183
ShoppingMall    208
Spa             183
VRDeck          188
Name            200
Transported       0
dtype: int64

There are multiple strategies to handle missing data

- Removing all rows or all columns containing missing data.
- Filling all missing values with a value (mean in continouos or mode in categorical for example).
- Filling all missing values with an algorithm.

For this exercise, because we have such low amount of null values, we will drop rows containing any missing value. 

In [61]:
spaceship=spaceship.dropna()

In [62]:
spaceship.isna().sum()

PassengerId     0
HomePlanet      0
CryoSleep       0
Cabin           0
Destination     0
Age             0
VIP             0
RoomService     0
FoodCourt       0
ShoppingMall    0
Spa             0
VRDeck          0
Name            0
Transported     0
dtype: int64

- **Cabin** is too granular - transform it in order to obtain {'A', 'B', 'C', 'D', 'E', 'F', 'G', 'T'}

In [63]:
spaceship['Cabin'].unique()

array(['B/0/P', 'F/0/S', 'A/0/S', ..., 'G/1499/S', 'G/1500/S', 'E/608/S'],
      dtype=object)

In [64]:
spaceship['Cabin'] = spaceship['Cabin'].apply(lambda x: x[0] if pd.notnull(x) else np.nan)

In [65]:
spaceship['Cabin'].unique()

array(['B', 'F', 'A', 'G', 'E', 'C', 'D', 'T'], dtype=object)

- Drop PassengerId and Name

In [66]:
spaceship = spaceship.drop(['PassengerId','Name'], axis=1)

In [67]:
spaceship.shape

(6606, 12)

- For non-numerical columns, do dummies.

In [68]:
spaceship.dtypes

HomePlanet       object
CryoSleep        object
Cabin            object
Destination      object
Age             float64
VIP              object
RoomService     float64
FoodCourt       float64
ShoppingMall    float64
Spa             float64
VRDeck          float64
Transported        bool
dtype: object

In [69]:
spaceship['HomePlanet'].unique()

array(['Europa', 'Earth', 'Mars'], dtype=object)

In [77]:
#from sklearn.preprocessing import OneHotEncoder

#cat = [df[col].unique() for col in spaceship['HomePlanet','Cabin', 'Destination','CryoSleep','VIP']]
#ohe = OneHotEncoder(sparse_output=False, categories=cat) 

#ohe.fit(spaceship[['HomePlanet','Cabin', 'Destination','CryoSleep','VIP']], drop="first") 
#spaceship_trans_np = ohe.transform(spaceship[['HomePlanet','Cabin', 'Destination','CryoSleep','VIP']])
#spaceship_trans_np

In [71]:
from sklearn.preprocessing import OneHotEncoder

categorical_cols = ['HomePlanet', 'Cabin', 'Destination', 'CryoSleep', 'VIP']

cat = [spaceship[col].unique() for col in categorical_cols]

ohe = OneHotEncoder(sparse_output=False, categories=cat)

ohe.fit(spaceship[categorical_cols]) 
spaceship_trans_np = ohe.transform(spaceship[categorical_cols])

spaceship_trans_np


array([[1., 0., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 1., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 1., 0.]])

In [73]:
spaceship2 = pd.DataFrame(spaceship_trans_np, columns=ohe.get_feature_names_out(), index=spaceship.index)
spaceship2

HomePlanet_Europa  HomePlanet_Earth  HomePlanet_Mars  Cabin_B  Cabin_F  \
0                   1.0               0.0              0.0      1.0      0.0   
1                   0.0               1.0              0.0      0.0      1.0   
2                   1.0               0.0              0.0      0.0      0.0   
3                   1.0               0.0              0.0      0.0      0.0   
4                   0.0               1.0              0.0      0.0      1.0   
...                 ...               ...              ...      ...      ...   
8688                1.0               0.0              0.0      0.0      0.0   
8689                0.0               1.0              0.0      0.0      0.0   
8690                0.0               1.0              0.0      0.0      0.0   
8691                1.0               0.0              0.0      0.0      0.0   
8692                1.0               0.0              0.0      0.0      0.0   

      Cabin_A  Cabin_G  Cabin_E  Cabin_C  Cabin_D  Cabin_T  \
0         0.0      0.0      0.0      0.0      0.0      0.0   
1         0.0      0.0      0.0      0.0      0.0      0.0   
2         1.0      0.0      0.0      0.0      0.0      0.0   
3         1.0      0.0      0.0      0.0      0.0      0.0   
4         0.0      0.0      0.0      0.0      0.0      0.0   
...       ...      ...      ...      ...      ...      ...   
8688      1.0      0.0      0.0      0.0      0.0      0.0   
8689      0.0      1.0      0.0      0.0      0.0      0.0   
8690      0.0      1.0      0.0      0.0      0.0      0.0   
8691      0.0      0.0      1.0      0.0      0.0      0.0   
8692      0.0      0.0      1.0      0.0      0.0      0.0   

      Destination_TRAPPIST-1e  Destination_PSO J318.5-22  \
0                         1.0                        0.0   
1                         1.0                        0.0   
2                         1.0                        0.0   
3                         1.0                        0.0   
4                         1.0                        0.0   
...                       ...                        ...   
8688                      0.0                        0.0   
8689                      0.0                        1.0   
8690                      1.0                        0.0   
8691                      0.0                        0.0   
8692                      1.0                        0.0   

      Destination_55 Cancri e  CryoSleep_False  CryoSleep_True  VIP_False  \
0                         0.0              1.0             0.0        1.0   
1                         0.0              1.0             0.0        1.0   
2                         0.0              1.0             0.0        0.0   
3                         0.0              1.0             0.0        1.0   
4                         0.0              1.0             0.0        1.0   
...                       ...              ...             ...        ...   
8688                      1.0              1.0             0.0        0.0   
8689                      0.0              0.0             1.0        1.0   
8690                      0.0              1.0             0.0        1.0   
8691                      1.0              1.0             0.0        1.0   
8692                      0.0              1.0             0.0        1.0   

      VIP_True  
0          0.0  
1          0.0  
2          1.0  
3          0.0  
4          0.0  
...        ...  
8688       1.0  
8689       0.0  
8690       0.0  
8691       0.0  
8692       0.0  

[6606 rows x 18 columns]

In [76]:
spaceship2.dtypes

HomePlanet_Europa            float64
HomePlanet_Earth             float64
HomePlanet_Mars              float64
Cabin_B                      float64
Cabin_F                      float64
Cabin_A                      float64
Cabin_G                      float64
Cabin_E                      float64
Cabin_C                      float64
Cabin_D                      float64
Cabin_T                      float64
Destination_TRAPPIST-1e      float64
Destination_PSO J318.5-22    float64
Destination_55 Cancri e      float64
CryoSleep_False              float64
CryoSleep_True               float64
VIP_False                    float64
VIP_True                     float64
dtype: object

In [ ]:
#split numerical values of spaceship
#concat numerical df and spaceship2
#define x and y
#train test split

In [80]:
numerical_df = spaceship.select_dtypes(include=['number'])

In [81]:
concatenated_df = pd.concat([spaceship2, numerical_df], axis=1)

**Perform Train Test Split**

In [82]:
X = concatenated_df
y = spaceship['Transported']

In [83]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state=0)

**Model Selection**

In this exercise we will be using **KNN** as our predictive model.

In [84]:
from sklearn.neighbors import KNeighborsClassifier


In [90]:
knn = KNeighborsClassifier(n_neighbors=9)

In [91]:
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=9)

- Evaluate your model's performance. Comment it

In [92]:
pred = knn.predict(X_test)
pred

array([ True,  True,  True, ...,  True,  True,  True])

In [93]:
y_test.values

array([ True, False,  True, ...,  True,  True,  True])

In [94]:
print(f"The accuracy of the model is {knn.score(X_test, y_test)*100: .2f}%")

The accuracy of the model is  77.99%


In [ ]:
# The model is 77.99% accurate which is a good rate. I used KNeighborsClassifier because the target is a boolean. 